# Use Amazon Linux 2 so we can install Docker and jq
FROM amazonlinux:2

# Install Docker CLI, jq, and AWS CLI v2
RUN yum update -y && \
    yum install -y unzip curl jq docker && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip
