FROM amazonlinux:2

RUN yum update -y && \
    amazon-linux-extras enable docker && \
    yum install -y docker jq which unzip curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip
